# Generated by Django 4.0.3 on 2022-03-06 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(-99),
                related_name="module_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=models.SET(-99),
                related_name="module_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
