# Generated by Django 4.0.3 on 2022-03-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_module_created_by_alter_module_modified_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="module",
            old_name="updated_at",
            new_name="updated_date",
        ),
    ]
