# Generated by Django 4.0.3 on 2022-04-07 22:33

from django.conf import settings
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_project_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(projects.models.get_deleted_user_instance),
                related_name="module_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=models.SET(projects.models.get_deleted_user_instance),
                related_name="module_modified_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
