# Generated by Django 4.0.4 on 2022-05-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_created_by_alter_project_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="created_by",
            new_name="owner",
        ),
    ]
