# Generated by Django 4.0.4 on 2022-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
