# Generated by Django 4.0.4 on 2022-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_about_me_user_avatar_user_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_me",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
