# Generated by Django 4.0.4 on 2022-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_about_me_alter_user_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
    ]
