# Generated by Django 4.0.4 on 2022-10-19 23:34

from django.db import migrations, models
import rattletest.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=rattletest.users.models.User.user_profile_avatar_path),
        ),
    ]
