# Generated by Django 4.0.3 on 2022-03-06 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcases", "0003_testcase_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tc_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
