# Generated by Django 4.0.3 on 2022-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0005_testcase_module_alter_testcase_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="attachment",
            field=models.FileField(
                default=1, max_length=255, upload_to="uploads/% Y/% m/% d/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testcase",
            name="priority",
            field=models.IntegerField(
                blank=True,
                choices=[(10, "Low"), (20, "Medium"), (30, "High")],
                default=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="severity",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (10, "Trivial"),
                    (20, "Minor"),
                    (30, "Normal"),
                    (40, "Major"),
                    (50, "Critical"),
                ],
                default=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(10, "Draft"), (20, "In Review"), (30, "Final")],
                default=10,
                null=True,
            ),
        ),
    ]
