# Generated by Django 4.0.3 on 2022-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0006_testcase_attachment_alter_testcase_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="attachment",
            field=models.FileField(max_length=255, upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
