# Generated by Django 4.0.4 on 2022-04-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_created_by_alter_project_members"),
        ("testcases", "0009_alter_testcase_created_by_alter_testcase_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcases",
                to="projects.module",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcases",
                to="projects.project",
            ),
        ),
    ]
